In [1]:
import torch
import numpy as np
torch.manual_seed(1)
# torch.cat(tensors, dim=0, out=None)
# Concatenates the given sequence of seq tensors in the given dimension. 
# All tensors must either have the same shape (except in the concatenating dimension) or be empty.


In [9]:
# Example 1
x1 = torch.randn(2,4)
print(x1)
print('x1.size() = {s}'.format(s=x1.size()))

x2 = torch.cat((x1,x1),0)
print('\n',x2)
print('x2.size() = {s}'.format(s=x2.size()))

x3 = torch.cat((x1,x1),1)
print('\n',x3)
print('x3.size() = {s}'.format(s=x3.size()))

tensor([[-1.1900,  0.2783, -0.2173,  1.1211],
        [ 0.5826, -0.5303, -0.0781,  0.4046]])
x1.size() = torch.Size([2, 4])

 tensor([[-1.1900,  0.2783, -0.2173,  1.1211],
        [ 0.5826, -0.5303, -0.0781,  0.4046],
        [-1.1900,  0.2783, -0.2173,  1.1211],
        [ 0.5826, -0.5303, -0.0781,  0.4046]])
x2.size() = torch.Size([4, 4])

 tensor([[-1.1900,  0.2783, -0.2173,  1.1211, -1.1900,  0.2783, -0.2173,  1.1211],
        [ 0.5826, -0.5303, -0.0781,  0.4046,  0.5826, -0.5303, -0.0781,  0.4046]])
x3.size() = torch.Size([2, 8])


In [18]:
# Example 2
x = torch.randn(2,3)
y = torch.randn(1,3)

print(x)
print('x.size() = {s}\n\n'.format(s=x.size()))

print(y)
print('y.size() = {s}\n\n'.format(s=y.size()))

z = torch.cat((x,y),0)
print(z)
print('z.size() = {s}\n\n'.format(s=z.size()))

# If w = torch.cat((x,y),1) , it will be wrong,because if you want to cat in dim1 , dim0

tensor([[-2.3388,  0.8742,  1.4090],
        [-0.9874,  0.8452,  0.3652]])
x.size() = torch.Size([2, 3])


tensor([[-1.0773,  1.2123, -1.0356]])
y.size() = torch.Size([1, 3])


tensor([[-2.3388,  0.8742,  1.4090],
        [-0.9874,  0.8452,  0.3652],
        [-1.0773,  1.2123, -1.0356]])
z.size() = torch.Size([3, 3])


