In [1]:
import torch
import numpy as np
# torch.max 
# torch.max(input, dim, keepdim=False, out=None) -> (Tensor, LongTensor) it's a tuple 
# More detail you can see https://pytorch.org/docs/stable/torch.html

In [10]:
x1 = torch.randn(1, 3)
print(x1)
print(x1.shape,'\n\n')

y1 = torch.max(x1)
print(y1)

tensor([[ 0.4870, -0.6830, -2.4234]])
torch.Size([1, 3]) 


tensor(0.4870)


In [12]:
x2 = torch.randn(3, 3)
print(x2)
print(x2.shape,'\n\n')

# torch.max(x, 0) 輸出每個直行中的最大值, 並且給出其在該行中的索引值
y2 = torch.max(x2, 0)
print(y2)

tensor([[-0.3302,  0.0905, -2.2868],
        [-1.1429,  1.7783, -0.6607],
        [ 0.2931,  0.8682,  1.3410]])
torch.Size([3, 3]) 


(tensor([0.2931, 1.7783, 1.3410]), tensor([2, 1, 2]))


In [17]:
x3 = torch.randn(3, 3)
print(x3)
print(x3.shape,'\n\n')

# torch.max(x, 0) 輸出每個橫列中的最大值, 並且給出其在該列中的索引值
y3 = torch.max(x3, 1)
print(y3)

tensor([[ 0.3923, -0.9009, -1.3612],
        [ 0.6998, -1.6428,  0.7614],
        [ 0.7039,  0.3317, -0.0942]])
torch.Size([3, 3]) 


(tensor([0.3923, 0.7614, 0.7039]), tensor([0, 2, 0]))
<class 'tuple'>
2


In [ ]:
# torch.max()[0]， 只返回最大值的每個數 
# troch.max()[1]， 只返回最大值的每個索引