In [1]:
import torch

In [22]:
#x1 = torch.Tensor([[[1, 2, 3],[4, 5, 6]]])
# More detail please go to https://pytorch.org/docs/stable/tensors.html
# torch.view() Returns a new tensor with the same data as the self tensor but of a different shape.
x1 = torch.Tensor([[1, 2, 3], [4, 5, 6]])
x2 = torch.Tensor([1, 2, 3, 4, 5, 6])
print(x1)
print(x2)
print('x1.shape = {s}'.format(s=x1.shape))
print('x2.shape = {s}\n\n'.format(s=x2.shape))

y1 = x1.view(6, 1)
y2 = x2.view(1, 6)
print(y1)
print(y2)
print('y1.shape = {s}'.format(s=y1.shape))
print('y2.shape = {s}\n\n'.format(s=y2.shape))

# -1 can auto input another number about the tensor
# 6 ===>(3,-1) mean -1 = 2
z1 = x1.view(3, -1)
z2 = x2.view(-1, 3)
print(z1)
print(z2)
print('z1.shape = {s}'.format(s=z1.shape))
print('z2.shape = {s}\n\n'.format(s=z2.shape))

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([1., 2., 3., 4., 5., 6.])
x1.shape = torch.Size([2, 3])
x2.shape = torch.Size([6])


tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.]])
tensor([[1., 2., 3., 4., 5., 6.]])
y1.shape = torch.Size([6, 1])
y2.shape = torch.Size([1, 6])


tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
z1.shape = torch.Size([3, 2])
z2.shape = torch.Size([2, 3])


