In [1]:
import torch
import numpy as np
# torch.squeeze(), torch.unsqueeze() example

In [12]:
x1 = torch.randn(1, 3)
print(x1.shape)
print(x1,'\n\n')

y1 = torch.unsqueeze(x1, 1)
print(y1.shape)
print(y1,'\n\n')

z1 = x1.unsqueeze(0)
print(z1.shape)
print(z1,'\n\n')

w1 = torch.squeeze(z1)
print(w1.shape)
print(w1)


torch.Size([1, 3])
tensor([[1.5891, 1.4483, 0.2205]]) 


torch.Size([1, 1, 3])
tensor([[[1.5891, 1.4483, 0.2205]]]) 


torch.Size([1, 1, 3])
tensor([[[1.5891, 1.4483, 0.2205]]]) 


torch.Size([3])
tensor([1.5891, 1.4483, 0.2205])


In [9]:
x2 = torch.randn(3)
print(x2)
print(x2.shape)

y2 = x2.unsqueeze(0)
print(y2.shape)

tensor([-0.5283,  0.2551, -0.9952])
torch.Size([3])
torch.Size([1, 3])
