In [1]:
import torch
import numpy as np
from torch.autograd import Variable

In [55]:
tensor = torch.tensor([[3,4],[5,7]],requires_grad=True,dtype=torch.float) 
                        # Only dtype = float can require gradients
                        # Create a tensor and set requires_grad=True to track computation with it
print(tensor)
print(tensor*tensor)
print(tensor.norm())    # Return tensor norm
print(tensor.grad)      # Before backward(),grad is not exist

tensor([[3., 4.],
        [5., 7.]], requires_grad=True)
tensor([[ 9., 16.],
        [25., 49.]], grad_fn=<ThMulBackward>)
tensor(9.9499, grad_fn=<NormBackward0>)
None


In [47]:
Compute = torch.mean(tensor*tensor) # 1/4 * sum(tensor^2)
print(Compute)
print(Compute.type())
Compute.backward()                  # Backpropagation

tensor(24.7500, grad_fn=<MeanBackward1>)
torch.FloatTensor


In [48]:
print(tensor.grad)                  # d(Compute)/d(tensor)

tensor([[1.5000, 2.0000],
        [2.5000, 3.5000]])


In [54]:
# Example 2
Tensor = torch.ones(3,3)
Tensor = Tensor*5 + 17       # Build a 3*3 matrix , value = 1*5 + 17

print(Tensor.requires_grad)  # At the beginning , requires_grad = False
Tensor.requires_grad = True
print(Tensor.requires_grad)  # Change requires_grad to True
print(Tensor)

False
True
tensor([[22., 22., 22.],
        [22., 22., 22.],
        [22., 22., 22.]], requires_grad=True)
