In [84]:
import torch
import numpy as np
# Show version
print(torch.__version__)
print(np.__version__)

0.4.1
1.14.5


In [99]:
ndata = np.arange(6).reshape(2,3)   # 2*3 matrix
tdata = torch.from_numpy(ndata)     # use from_numpy change numpy to tensor
ndata2 = tdata.numpy()              # Use numpy() change tensor to numpy 
print(tdata)
print('type(tdata) =',tdata.type()) # If variable is a tensor ,you should use variable.type() to understand it's type
                                    # Use type(variable) always show <class 'torch.Tensor'> , can not know the detail
print(ndata2)
print('type(ndata2) =',type(ndata2))

tensor([[0, 1, 2],
        [3, 4, 5]], dtype=torch.int32)
type(tdata) = torch.IntTensor
[[0 1 2]
 [3 4 5]]
type(ndata2) = <class 'numpy.ndarray'>


In [94]:
# Introduce some math operation 
data = np.array([-1, -2, 1, 2])
tensor = torch.FloatTensor(data)  # sin must to use float
print(tensor)
print(tensor.type())              # Use type() to know the type
# Sin function
print(np.sin(data))
print(torch.sin(tensor))

tensor([-1., -2.,  1.,  2.])
torch.FloatTensor
[-0.84147098 -0.90929743  0.84147098  0.90929743]
tensor([-0.8415, -0.9093,  0.8415,  0.9093])


In [87]:
# Sigmoid function
print(torch.sigmoid(tensor))

tensor([0.2689, 0.1192, 0.7311, 0.8808])


In [88]:
# Abs function
print(np.abs(data))
print(torch.abs(tensor))

[1 2 1 2]
tensor([1., 2., 1., 2.])


In [89]:
# Exp function
print(np.exp(data))
print(torch.exp(tensor))

[0.36787944 0.13533528 2.71828183 7.3890561 ]
tensor([0.3679, 0.1353, 2.7183, 7.3891])


In [90]:
# Mean function
# Returns the mean value of all elements in the input tensor.
print(np.mean(data))
print(torch.mean(tensor))

0.0
tensor(0.)


In [91]:
### Matrix operation ###
# Matrix multiplication
Matrix = np.array([[1,2],[3,4]])
Tensor = torch.FloatTensor(Matrix)

# print(Tensor)
print(np.matmul(Matrix,Matrix))

# torch use mm function to do matrix multiplication
# Performs a matrix multiplication of the matrices mat1 and mat2.
# If mat1 is a (n×m) tensor, mat2 is a (m×p) tensor
# ,out will be a (n×p) tensor.
print(torch.mm(Tensor,Tensor)) 

[[ 7 10]
 [15 22]]
tensor([[ 7., 10.],
        [15., 22.]])


In [92]:
print(Tensor * Tensor) # 

tensor([[ 1.,  4.],
        [ 9., 16.]])


In [93]:
# Computes the dot product (inner product) of two tensors.
print(torch.dot(torch.Tensor([5, 3]), torch.Tensor([2, 4]))) # 5*2 + 3*4

tensor(22.)


In [ ]:
# More details about math operation in torch can be found in: http://pytorch.org/docs/torch.html#math-operations